#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-MIME-Base64
Version  : 3.15
Release  : 27
URL      : http://www.cpan.org/CPAN/authors/id/G/GA/GAAS/MIME-Base64-3.15.tar.gz
Source0  : http://www.cpan.org/CPAN/authors/id/G/GA/GAAS/MIME-Base64-3.15.tar.gz
Summary  : 'The RFC 2045 encodings; base64 and quoted-printable'
Group    : Development/Tools
License  : Artistic-1.0-Perl
Requires: perl-MIME-Base64-perl = %{version}-%{release}
BuildRequires : buildreq-cpan

%description
This package contains a base64 encoder/decoder and a quoted-printable
encoder/decoder.  These encoding methods are specified in RFC 2045 -
MIME (Multipurpose Internet Mail Extensions).

%package perl
Summary: perl components for the perl-MIME-Base64 package.
Group: Default
Requires: perl-MIME-Base64 = %{version}-%{release}

%description perl
perl components for the perl-MIME-Base64 package.


%prep
%setup -q -n MIME-Base64-3.15
cd %{_builddir}/MIME-Base64-3.15

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot} INSTALLDIRS=vendor
else
./Build install --installdirs=vendor --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*
## Remove excluded files
rm -f %{buildroot}/usr/share/man/man3/MIME::QuotedPrint.3
rm -f %{buildroot}/usr/share/man/man3/MIME::Base64.3

%files
%defattr(-,root,root,-)

%files perl
%defattr(-,root,root,-)
/usr/lib/perl5/vendor_perl/5.30.2/x86_64-linux-thread-multi/MIME/Base64.pm
/usr/lib/perl5/vendor_perl/5.30.2/x86_64-linux-thread-multi/MIME/QuotedPrint.pm
/usr/lib/perl5/vendor_perl/5.30.2/x86_64-linux-thread-multi/auto/MIME/Base64/Base64.so
